security:
    encoders:
        BestWishes\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        bw_user_provider:
            entity:
                class: BestWishes\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                csrf_token_generator: security.csrf.token_manager
                use_referer: true

            logout:       true
            anonymous:    true
            remember_me:
                secret:   'b%kernel.secret%w'
                lifetime: 15778463 # 6 months in seconds
                path:     /
            guard:
                authenticators:
                    - BestWishes\Security\FormAuthenticator

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

acl:
    connection: default
    tables:
        class:                '%tables_prefix%acl_classes'
        entry:                '%tables_prefix%acl_entries'
        object_identity:      '%tables_prefix%acl_object_identities'
        object_identity_ancestors:  '%tables_prefix%acl_object_identity_ancestors'
        security_identity:    '%tables_prefix%acl_security_identities'
