# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /

            logout:       true
            anonymous:    true
            remember_me:
                secret:   'b%secret%w'
                lifetime: 15778463 # 6 months in seconds
                path:     /

    acl:
        connection: default
        tables:
            class:                '%database_prefix%acl_classes'
            entry:                '%database_prefix%acl_entries'
            object_identity:      '%database_prefix%acl_object_identities'
            object_identity_ancestors:  '%database_prefix%acl_object_identity_ancestors'
            security_identity:    '%database_prefix%acl_security_identities'

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
