
services:
    # Override the system ACLs to be able to use our own permission masks
    bw.acl.permission_map:
        class: AppBundle\Security\Acl\Permissions\BestWishesPermissionMap

    bw.acl.acl_voter:
        class: AppBundle\Security\Acl\Voter\BestWishesAclVoter
        parent: security.acl.voter.basic_permissions
        arguments:
            index_3: '@bw.acl.permission_map'
        tags:
            - { name: security.voter }
