services:

    bw.list_event_manager:
        class: AppBundle\Manager\ListEventManager
        arguments: ["@doctrine.orm.default_entity_manager"]

    bw.twig.security_extension:
        class: AppBundle\Twig\Extension\BestWishesSecurityExtension
        arguments:
            - "@security.authorization_checker"
            - "@bw.security_context"
        tags:
            - { name: twig.extension }

    bw.security_context:
        class: AppBundle\Security\Core\BestWishesSecurityContext
        arguments: [ "@security.acl.provider" ]

    bw.security_acl_manager:
        class: AppBundle\Security\AclManager
        arguments: [ "@security.acl.provider" ]

    bw.mailer:
        class: AppBundle\Mailer\Mailer
        arguments:
            - "@mailer"
            - "@router"
            - "@templating"
            - "%global_from_email_address%"

    bw.util.user_manipulator:
        class: AppBundle\Util\UserManipulator
        arguments:
            - "@fos_user.user_manager"
            - "@event_dispatcher"
            - "@request_stack"

    bw.gift_subscriber:
        class: AppBundle\EventSubscriber\GiftSubscriber
        arguments:
            - "@fos_user.user_manager"
            - "@bw.security_context"
            - "@bw.mailer"
        tags:
            - { name: kernel.event_subscriber }

    bw.tblprefix_subscriber:
        class: AppBundle\EventSubscriber\TablePrefixSubscriber
        arguments: [ '%database_prefix%' ]
        tags:
            - { name: doctrine.event_subscriber }

    bw.locale_subscriber:
        class: AppBundle\EventSubscriber\LocaleSubscriber
        arguments: [ '%kernel.default_locale%' ]
        tags:
            - { name: kernel.event_subscriber }
