<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListEventRepository extends EntityRepository
{
    public function findAllActive() {
        return $this->createQueryBuilder('le')
            ->where('le.isActive = true')
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->setResultCacheLifetime(600)
            ->getResult();
    }
}
